### ISSUE TITLE
Consider VS Code extesion

### ISSUE THREAD

**Issue by huruka** [polarmutex/beancount-language-server#26]
Hi Brian, I am wondering if you know there is a vscode extension for beancount(https://github.com/Lencerf/vscode-beancount), and whether it can be integrated with your project. 
At present, the extension has achieved most of the basic functions (although there are still many things that can be improved).

**Comment by bryall** [comment]
Hey huruka, 

I knew of the extension you linked. I created this at first since mainly use neovim to edit my beancount files. And I actually created my own [vs-code extension](https://github.com/bryall/vscode-beancount-langserver) that wraps my LSP. I really can not integrate my LSP with the one you linked since Lencerf's is an internal vs-code extension and mine is a wrapped external LSP extension. My LSP will have to external since I rely on tree-sitter to perform many of the lsp functions. My mail goal is to improve the usability of beancount on neovim. I plan on updating my vscode plugin since I really do not have to write more code to get the features ported over.

At present I believe my lsp has all the features of the one you linked. I plan on adding more features over the year like code actions to sort transactions. I will be thankful for any issues/comments to make the projects better. I plan on making this project more public once I smooth out the rough edges.
